sudo: false
language: python
python: 2.7
cache:
  pip: true
  directories:
  - "./env/"
  - "./gaenv/"

env:
- GAE_ZIP=google_appengine_1.9.36.zip

matrix:
  include:
  - os: osx
    language: generic

# https://github.com/travis-ci/travis-ci/issues/738#issuecomment-11179888
before_script:
- pip install -r requirements-dev.txt
- wget -nv https://storage.googleapis.com/appengine-sdks/featured/${GAE_ZIP}
- unzip -q ${GAE_ZIP} -d ${HOME}

script:
- make test-ci

before_deploy:
- make release-ci
- FILENAME_CI=dist/Grow-SDK-${TRAVIS_OS_NAME/linux/Linux}-${TRAVIS_TAG}.zip
- FILENAME_CI=${FILENAME_CI/osx/Mac}

deploy:
  provider: releases
  api_key:
    secure: Cy6rwRChlvwcCswxTVeAj7V4K+jX47njPp36avLF9Ya6Okzf2OEFLHg6UoAF0/1GhU07Y0Qz46TksFXbss3wE3eVsfP5sWpfzCzLgE4ZNH6TqfAKgEFr6uJ5IEcDKZdVNQtCr0LRrxCcUOV387rnOpyy85o2SM0lp/6VZEQpVHA=
  draft: true
  file: ${FILENAME_CI}
  on:
    tags: true
  skip_cleanup: true

notifications:
  slack:
    on_success: change
    rooms:
    - secure: h4w4c5VDJcRs/nVMI3MK+qM3bazQ/XOiLPK+YfMV3Ekr51uhkqY9f2Jl5WNDuWAjP+2kjar/2iWW6irNxOSkiiXpMKjm7wJPYsP+3wFvLMlFT3Ri/0Mdfm7ZTEeHCyAR8kslcAfKJvwvl+WEm8ziDgu3vRvUF+0R4J/iTpniwKk=
