language: python
python:
  - 2.7
before_install:
#  - git submodule update --init --recursive
  - pip install -r requirements.txt
#  - cd grow/submodules/babel
#  - python setup.py import_cldr
#  - cd ../../../
script: python run_tests.py
