name: 'Release Please'
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: test-release-please
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v2
      - if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - if: ${{ steps.release.outputs.release_created }}
        name: Install
        run: |
          pip3 install -U pip
          pip3 install -U pipenv
          pip3 install pyyaml -U --force
          pipenv run pip3 install pip
          pipenv install --dev
          pipenv run pip3 install pyyaml -U --force
      - if: ${{ steps.release.outputs.release_created }}
        name: Build UI assets
        run: |
          make build-ui
      - if: ${{ steps.release.outputs.release_created }}
        name: Build package
        run: |
          rm -rf dist
          pipenv run python setup.py sdist bdist_wheel
      - if: ${{ steps.release.outputs.release_created }}
        name: Upload to PyPi
        run: |
          pipenv run twine upload dist/grow*
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      - if: ${{ steps.release.outputs.release_created }}
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - if: ${{ steps.release.outputs.release_created }}
        name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: grow/base
      - if: ${{ steps.release.outputs.release_created }}
        name: Push grow/base:main
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: grow_version=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      - if: ${{ steps.release.outputs.release_created }}
        name: Push grow/base:VERSION
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: grow/base:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: grow_version=${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}